api = "0.7"

[buildpack]
  description = "A buildpack for installing app dependencies via `bundle`"
  homepage = "https://github.com/paketo-buildpacks/bundle-install"
  id = "neeto-deploy/bundle-install"
  keywords = ["ruby", "bundler"]
  name = "Paketo Buildpack for Bundle Install"
  sbom-formats = ["application/vnd.cyclonedx+json", "application/spdx+json", "application/vnd.syft+json"]
  version = "0.8.18"

  [[buildpack.licenses]]
    type = "Apache-2.0"
    uri = "https://github.com/paketo-buildpacks/bundle-install/blob/main/LICENSE"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

[[targets]]
  os = "linux"
  arch = "amd64"

[[targets]]
  os = "linux"
  arch = "arm64"

[[stacks]]
  id = "*"
